<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/template/CSS/style-v5.css" rel="stylesheet" type="text/css">
        <link href="/template/CSS/<?= $style ?>" rel="stylesheet" type="text/css">
        <title><?= $title ?></title>
    </head>

    <body>
        <nav>
            <ul>
                <li>
                    <a href="/seasons"><?= $lang['seasons'] ?></a>
                </li>
                <li>
                    <a href="/statistics"><?= $lang['statistics'] ?></a>
                </li>
            </ul>
        </nav>

        <article>
            <?= $this->presenter->writeView() ?>
        </article>
    </body>
</html>