<div class="records">
    <h1>
        <a href="/seasons/<?= $season['season_year'] . '/' . $season['season_name'] ?>">
            <?= $season['season_year'] . ' ' . $season['season_name'] ?>
        </a>
        -
        <a href="/seasons/<?= $season['season_year'] . '/' . $season['season_name'] . '/' . $level ?>">
            <?= $level ?>
        </a>
    </h1>

    <button class="btn btn-primary"
            onclick="window.location.href='/manage-record/<?= $url ?>'">
        <?= $lang['add-record'] ?>
    </button>

    <div class="records-list">
        <?php if (!isset($records) || empty($records)): ?>
            <h3><?= $lang['no-records'] ?></h3>
        <?php endif; ?>
        <?php foreach ($records as $record): ?>
            <div class="records-list-item">
                <a href="/profile/<?= $record['record_holder'] ?>"><i><?= $record['record_holder'] ?></i></a>
                <p><?= $record['record_time'] ?></p>
                <img onclick="show_remove('/seasons/<?= $url . '/remove/' . $record['record_id'] ?>')"
                     src="/assets/bin-icon.png" alt="Remove">
            </a>
        <?php endforeach; ?>

    </div>
</div>
<div class="remove">
    <div class="remove-tab">
        <p>Are you sure you want to remove this record?</p>
        <div class="remove-tab-buttons">
            <button class="btn btn-primary" onclick="remove()">Remove</button>
            <button class="btn btn-gray" onclick="hide_remove()">Cancel</button>
        </div>
    </div>
</div>

<script src="/template/app.js"></script>