<div class="records">
    <h1><?= $season['season_year'] . ' ' . $season['season_name']
            . ' - ' . $level ?></h1>

    <button class="btn btn-primary"
            onclick="window.location.href='/manage-record/<?= $url ?>'">
        <?= $lang['add-record'] ?>
    </button>

    <div class="records-list">
        <?php if (!isset($records) || empty($records)): ?>
            <h3><?= $lang['no-records'] ?></h3>
        <?php endif; ?>
        <?php foreach ($records as $record): ?>
            <a href="">
                <i><?= $record['record_holder'] ?></i>
                <p><?= $record['record_time'] ?></p>
            </a>
        <?php endforeach; ?>
    </div>
</div>