<div class="wrapper">
    <h1><?= $lang['add-record'] ?>:</h1>
    <h2><?= $season['season_year'] . ' ' . $season['season_name']
            . ' - ' . sprintf("%02d", $level) ?></h2>

    <form method="post">
        <input type="hidden" name="record_id">
        <input type="hidden" name="record_season" value="<?= $season['season_id'] ?>">
        <input type="hidden" name="record_level" value="<?= $level ?>">
        <label class="form-label" for="record_holder">
            <?= $lang['holder'] ?>: <span>*</span>
        </label>
        <input class="form-control <?= isset($errors['holder']) ? 'invalid' : '' ?>"
                type="text" name="record_holder" id="record_holder">
        <label class="form-label" for="record_time">
            <?= $lang['time'] ?>:  <span>*</span>
        </label>
        <input class="form-control <?= isset($errors['name']) ? 'invalid' : '' ?>"
                type="text" name="record_time" id="record_time">
        <input class="btn btn-primary mt-15" type="submit" value="<?= $lang['add-record'] ?>">
    </form>
</div>