<div class="manage">
    <h1><?= $lang['add-season'] ?>:</h1>

    <form method="post">
        <label class="form-label">
            <span><?= isset($errors['exists']) ? $errors['exists'] : '' ?></span>
        </label>
        <input type="hidden" name="season_id">
        <label class="form-label" for="season_year">
            <?= $lang['year'] ?>: <span>*</span>
        </label>
        <input class="form-control <?= isset($error['year']) ? 'invalid' : '' ?>"
               type="number" name="season_year" id="season_year">
        <label class="form-label" for="season_name">
            <?= $lang['time'] ?>: <span>*</span>
        </label>
        <input class="form-control <?= isset($error['name']) ? 'invalid' : '' ?>"
               type="text" name="season_name" id="season_name">
        <input class="btn btn-primary mt-15" type="submit" value="Add season">
    </form>
</div>