<div class="records">
    <h1><?= $season['season_year'] . ' ' . $season['season_name']?></h1>

    <div class="records-list">
        <?php foreach ($records as $record): ?>
            <a href="/seasons/<?= $season['season_year'] . '/' . 
                    $season['season_name'] . '/' . $record['record_level'] ?>">
                <b><?= sprintf("%02d", $record['record_level']) ?></b>
                <i><?= $record['record_holder'] ?></i>
                <?php if (empty($record['record_time']) || $record['record_time'] == ''): ?>
                    <p><?= $lang['no-record'] ?></p>
                <?php else: ?>
                    <p><?= $record['record_time'] ?></p>
                <?php endif; ?>
            </a>
        <?php endforeach; ?>
    </div>
</div>