<div class="records">
    <h1>2023 Winter</h1>

    <div class="records-list">
        <?php foreach ($records as $record): ?>
            <a href="/seasons/<?= $season['season_year'] . '/' . 
                    $season['season_name'] . '/' . $record['record_level'] ?>">
                <b><?= sprintf("%02d", $record['record_level']) ?></b>
                <i><?= $record['record_holder'] ?></i>
                <p><?= $record['record_time'] ?></p>
            </a>
        <?php endforeach; ?>
    </div>
</div>