<div class="wrapper">
    <h1><?= $lang['statistics'] ?>:</h1>

    <div class="list">
        <?php if (!isset($statistics) || empty($statistics)): ?>
            <h3><?= $lang['no-statistics'] ?></h3>
        <?php endif; ?>
        <?php foreach ($statistics as $statistic): ?>
            <div class="list-item">
                <a href="/profile/<?= $statistic['record_holder'] ?>">
                    <i><?= $statistic['record_holder'] ?></i>
                </a>
                <p><?= $statistic['record_number'] ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>